import React, { useState } from 'react';
import { 
  Recycle, 
  Plus, 
  Trash2, 
  Package, 
  MapPin, 
  Sparkles, 
  IndianRupee, 
  Scale, 
  Calendar,
  AlertCircle
} from 'lucide-react';

const CATEGORIES = [
  'Minerals & Construction',
  'Agriculture & Food',
  'Wood & Biomass',
  'Metals & Metallurgy',
  'Plastics & Polymers',
  'Paper & Packaging',
  'Chemicals & Solvents'
];

export default function WasteStreamsView({ 
  currentCompany, 
  myWasteListings, 
  onAddWaste, 
  onDeleteWaste,
  onNavigateSection
}) {
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  
  const [formData, setFormData] = useState({
    title: '',
    category: 'Minerals & Construction',
    quantity: '',
    unit: 'Tons',
    pricePerUnit: '',
    purityPercentage: 95,
    frequency: 'Recurring (Monthly)',
    location: currentCompany?.location || '',
    description: ''
  });

  const handleSubmit = async (e) => {
    e.preventDefault();
    await onAddWaste(formData);
    setIsAddModalOpen(false);
    setFormData({
      title: '',
      category: 'Minerals & Construction',
      quantity: '',
      unit: 'Tons',
      pricePerUnit: '',
      purityPercentage: 95,
      frequency: 'Recurring (Monthly)',
      location: currentCompany?.location || '',
      description: ''
    });
  };

  return (
    <div className="space-y-6 animate-fade-in">
      
      {/* Header Banner */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <Recycle className="w-5 h-5 text-emerald-600" />
            <h1 className="text-xl font-bold text-slate-900">Waste Streams & By-Products</h1>
          </div>
          <p className="text-slate-500 text-xs mt-1">
            Manage by-products generated by <strong className="text-slate-700">{currentCompany?.name}</strong>. 
            Once a contract is finalized and transferred, fulfilled stock is automatically deducted.
          </p>
        </div>

        <button
          onClick={() => setIsAddModalOpen(true)}
          className="inline-flex items-center space-x-2 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl shadow-md transition-all shrink-0"
        >
          <Plus className="w-4 h-4" />
          <span>+ Add Waste By-Product</span>
        </button>
      </div>

      {/* Streams List */}
      {myWasteListings.length === 0 ? (
        <div className="bg-white rounded-2xl border border-slate-200 p-12 text-center max-w-md mx-auto">
          <div className="w-14 h-14 rounded-2xl bg-emerald-50 text-emerald-600 flex items-center justify-center mx-auto mb-3">
            <Package className="w-7 h-7" />
          </div>
          <h3 className="font-bold text-slate-800 text-base">No waste streams listed yet</h3>
          <p className="text-slate-500 text-xs mt-1 mb-4 leading-relaxed">
            Turn your factory's disposal costs into secondary revenue! List your scrap, ash, slag, wood dust, or mash.
          </p>
          <button
            onClick={() => setIsAddModalOpen(true)}
            className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-xl shadow-sm"
          >
            Add Your First Waste Stream
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {myWasteListings.map((waste) => (
            <div
              key={waste.id}
              className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm hover:shadow-md transition-all flex flex-col justify-between"
            >
              <div>
                <div className="flex items-start justify-between">
                  <span className="text-[10px] font-bold text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-100">
                    {waste.category}
                  </span>
                  <button
                    onClick={() => onDeleteWaste(waste.id)}
                    className="text-slate-400 hover:text-red-600 p-1 rounded-md transition-colors"
                    title="Remove waste stream"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>

                <h3 className="font-bold text-slate-900 text-base mt-2">
                  {waste.title}
                </h3>

                <p className="text-xs text-slate-500 mt-1 line-clamp-2 leading-relaxed">
                  {waste.description || 'Verified industrial byproduct batch ready for dispatch.'}
                </p>

                <div className="mt-4 pt-3 border-t border-slate-100 grid grid-cols-3 gap-2 bg-slate-50 p-2.5 rounded-xl text-center text-xs">
                  <div>
                    <div className="text-[9px] text-slate-400 font-semibold uppercase">Quantity</div>
                    <div className="font-bold text-slate-800 mt-0.5">{waste.quantity} {waste.unit}</div>
                  </div>
                  <div>
                    <div className="text-[9px] text-slate-400 font-semibold uppercase">Price</div>
                    <div className="font-bold text-emerald-700 mt-0.5">₹{waste.pricePerUnit}/{waste.unit}</div>
                  </div>
                  <div>
                    <div className="text-[9px] text-slate-400 font-semibold uppercase">Purity</div>
                    <div className="font-bold text-slate-800 mt-0.5">{waste.purityPercentage}%</div>
                  </div>
                </div>
              </div>

              <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-400">
                <span className="flex items-center gap-1">
                  <MapPin className="w-3 h-3 text-slate-400" />
                  <span>{waste.location}</span>
                </span>
                <span>{waste.frequency}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Add Waste Stream Modal */}
      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full border border-slate-100 p-6 max-h-[90vh] overflow-y-auto">
            <h3 className="text-lg font-bold text-slate-900 mb-1">List Waste Stream / By-Product</h3>
            <p className="text-xs text-slate-500 mb-4">Make your plant's waste discoverable to buyers across the network.</p>

            <form onSubmit={handleSubmit} className="space-y-3.5">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Material Name *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Granulated Blast Furnace Slag, Kiln-Dried Sawdust"
                  value={formData.title}
                  onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                  className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Category</label>
                  <select
                    value={formData.category}
                    onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none bg-white"
                  >
                    {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Supply Frequency</label>
                  <select
                    value={formData.frequency}
                    onChange={(e) => setFormData({ ...formData, frequency: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none bg-white"
                  >
                    <option value="One-time Batch">One-time Batch</option>
                    <option value="Recurring (Weekly)">Recurring (Weekly)</option>
                    <option value="Recurring (Monthly)">Recurring (Monthly)</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-3 gap-2">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Quantity *</label>
                  <input
                    type="number"
                    required
                    min="1"
                    placeholder="100"
                    value={formData.quantity}
                    onChange={(e) => setFormData({ ...formData, quantity: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Unit</label>
                  <select
                    value={formData.unit}
                    onChange={(e) => setFormData({ ...formData, unit: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none bg-white"
                  >
                    <option value="Tons">Tons</option>
                    <option value="Kg">Kg</option>
                    <option value="Barrels">Barrels</option>
                    <option value="Liters">Liters</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Price / Unit ($) *</label>
                  <input
                    type="number"
                    required
                    min="1"
                    placeholder="25"
                    value={formData.pricePerUnit}
                    onChange={(e) => setFormData({ ...formData, pricePerUnit: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Purity (%)</label>
                  <input
                    type="number"
                    min="1"
                    max="100"
                    placeholder="95"
                    value={formData.purityPercentage}
                    onChange={(e) => setFormData({ ...formData, purityPercentage: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Plant Location</label>
                  <input
                    type="text"
                    placeholder="City, State"
                    value={formData.location}
                    onChange={(e) => setFormData({ ...formData, location: e.target.value })}
                    className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Technical Notes & Specifications</label>
                <textarea
                  rows="2"
                  placeholder="e.g. Moisture content, granulation size, chemical test data..."
                  value={formData.description}
                  onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                  className="w-full px-3 py-2 text-xs sm:text-sm border border-slate-300 rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"
                ></textarea>
              </div>

              <div className="flex justify-end space-x-2 pt-3 border-t">
                <button
                  type="button"
                  onClick={() => setIsAddModalOpen(false)}
                  className="px-4 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100 rounded-lg"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold rounded-lg shadow-sm"
                >
                  Publish Waste Stream
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
